# Generated by Django 5.2.17 on 2026-09-28 01:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0001_initial"),
        ("tiers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BonEntree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name="N° bon",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "reference_fournisseur",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        verbose_name="Réf. bon de livraison / facture fournisseur",
                    ),
                ),
                ("commentaire", models.TextField(blank=True)),
                (
                    "valide",
                    models.BooleanField(
                        default=False,
                        editable=False,
                        verbose_name="Validé (stock mis à jour)",
                    ),
                ),
                (
                    "date_validation",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bons_entree",
                        to="tiers.fournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bon d'entrée (réception)",
                "verbose_name_plural": "Bons d'entrée (réceptions)",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LigneBonEntree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite",
                    models.PositiveIntegerField(default=1, verbose_name="Quantité"),
                ),
                (
                    "prix_achat",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Prix d'achat unitaire",
                    ),
                ),
                (
                    "bon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="stock.bonentree",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogue.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne",
            },
        ),
        migrations.CreateModel(
            name="MouvementStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_mouvement",
                    models.CharField(
                        choices=[("E", "Entrée"), ("S", "Sortie")],
                        max_length=1,
                        verbose_name="Sens",
                    ),
                ),
                (
                    "motif",
                    models.CharField(
                        choices=[
                            ("ACHAT", "Réception fournisseur"),
                            ("VENTE", "Vente / facture"),
                            ("MAINT", "Pièce utilisée en maintenance"),
                            ("RETOUR", "Retour client"),
                            ("CASSE", "Casse / perte"),
                            ("INVENT", "Ajustement d'inventaire"),
                            ("AUTRE", "Autre"),
                        ],
                        default="AUTRE",
                        max_length=6,
                    ),
                ),
                ("quantite", models.PositiveIntegerField(verbose_name="Quantité")),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="N° de facture, de bon d'entrée, de dossier de maintenance...",
                        max_length=40,
                        verbose_name="Document lié",
                    ),
                ),
                ("commentaire", models.CharField(blank=True, max_length=255)),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mouvements",
                        to="catalogue.produit",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mouvement de stock",
                "verbose_name_plural": "Mouvements de stock",
                "ordering": ["-date", "-id"],
            },
        ),
    ]
