# Generated by Django 5.2.17 on 2026-09-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Entreprise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        default="TelecomPro",
                        max_length=150,
                        verbose_name="Raison sociale",
                    ),
                ),
                ("slogan", models.CharField(blank=True, max_length=200)),
                ("adresse", models.TextField(blank=True)),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                (
                    "ifu",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="N° IFU / NIF"
                    ),
                ),
                (
                    "rccm",
                    models.CharField(blank=True, max_length=50, verbose_name="N° RCCM"),
                ),
                ("logo", models.ImageField(blank=True, upload_to="entreprise/")),
                ("devise", models.CharField(default="FCFA", max_length=10)),
                (
                    "taux_tva_defaut",
                    models.DecimalField(
                        decimal_places=2,
                        default=18,
                        max_digits=5,
                        verbose_name="Taux TVA par défaut (%)",
                    ),
                ),
                (
                    "conditions_facture",
                    models.TextField(
                        blank=True,
                        default="Les marchandises vendues ne sont ni reprises ni échangées.",
                        verbose_name="Mentions en pied de facture",
                    ),
                ),
                (
                    "validite_proforma_jours",
                    models.PositiveIntegerField(
                        default=15, verbose_name="Validité des proformas (jours)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fiche entreprise",
                "verbose_name_plural": "Fiche entreprise",
            },
        ),
        migrations.CreateModel(
            name="Compteur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prefixe", models.CharField(max_length=10)),
                ("annee", models.PositiveIntegerField()),
                ("dernier_numero", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Compteur de numérotation",
                "verbose_name_plural": "Compteurs de numérotation",
                "unique_together": {("prefixe", "annee")},
            },
        ),
    ]
