# Generated by Django 5.2.17 on 2026-09-28 01:45

import django.db.models.deletion
import django.utils.timezone
import messagerie.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0001_initial"),
        ("tiers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalEnvoi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("code", models.CharField(blank=True, max_length=20)),
                ("destinataire", models.CharField(max_length=254)),
                ("sujet", models.CharField(max_length=200)),
                ("corps", models.TextField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ENVOYE", "Envoyé"),
                            ("ECHEC", "Échec"),
                            ("NON_ENVOYE", "Non envoyé (e-mail désactivé)"),
                        ],
                        max_length=10,
                    ),
                ),
                ("erreur", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Journal d'envoi",
                "verbose_name_plural": "Journal des envois",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ModeleMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("CMD_RECUE", "Client — confirmation de commande"),
                            ("CMD_STATUT", "Client — changement de statut de commande"),
                            (
                                "MAINT_DEPOT",
                                "Client — dépôt d'un appareil en maintenance",
                            ),
                            (
                                "MAINT_STATUT",
                                "Client — changement de statut de maintenance",
                            ),
                            (
                                "CONSEIL_REPONSE",
                                "Client — réponse à une demande de conseil",
                            ),
                            ("EQUIPE_CMD", "Équipe — nouvelle commande en ligne"),
                            ("EQUIPE_CONSEIL", "Équipe — nouvelle demande de conseil"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("sujet", models.CharField(max_length=200)),
                ("corps", models.TextField()),
            ],
            options={
                "verbose_name": "Modèle de message",
                "verbose_name_plural": "Modèles de messages",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="ParametresMessagerie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_actif",
                    models.BooleanField(
                        default=False,
                        help_text="Décoché : les notifications sont seulement enregistrées dans le journal.",
                        verbose_name="Envoi d'e-mails activé",
                    ),
                ),
                (
                    "smtp_hote",
                    models.CharField(
                        blank=True,
                        help_text="Ex : smtp.gmail.com",
                        max_length=150,
                        verbose_name="Serveur SMTP",
                    ),
                ),
                (
                    "smtp_port",
                    models.PositiveIntegerField(default=587, verbose_name="Port SMTP"),
                ),
                (
                    "smtp_utilisateur",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Utilisateur SMTP"
                    ),
                ),
                (
                    "smtp_mot_de_passe",
                    models.CharField(
                        blank=True,
                        help_text="Pour Gmail, utilisez un « mot de passe d'application ».",
                        max_length=150,
                        verbose_name="Mot de passe SMTP",
                    ),
                ),
                (
                    "smtp_tls",
                    models.BooleanField(
                        default=True, verbose_name="Utiliser STARTTLS (port 587)"
                    ),
                ),
                (
                    "smtp_ssl",
                    models.BooleanField(
                        default=False, verbose_name="Utiliser SSL (port 465)"
                    ),
                ),
                (
                    "expediteur_nom",
                    models.CharField(
                        default="TelecomPro",
                        max_length=100,
                        verbose_name="Nom de l'expéditeur",
                    ),
                ),
                (
                    "expediteur_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="Adresse de l'expéditeur",
                    ),
                ),
                (
                    "url_site",
                    models.URLField(
                        default="http://localhost:8000",
                        help_text="Utilisée pour les liens de suivi insérés dans les e-mails.",
                        verbose_name="Adresse publique du site",
                    ),
                ),
                (
                    "email_equipe",
                    models.EmailField(
                        blank=True,
                        help_text="Reçoit les alertes internes : nouvelle commande, nouvelle demande de conseil.",
                        max_length=254,
                        verbose_name="E-mail de l'équipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres de messagerie",
                "verbose_name_plural": "Paramètres de messagerie",
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jeton",
                    models.CharField(
                        default=messagerie.models._jeton,
                        editable=False,
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("nom", models.CharField(max_length=150)),
                (
                    "telephone",
                    models.CharField(max_length=30, verbose_name="Téléphone"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                ("sujet", models.CharField(max_length=200)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("ATTENTE", "En attente de réponse"),
                            ("REPONDU", "Répondu"),
                            ("CLOS", "Clos"),
                        ],
                        default="ATTENTE",
                        max_length=8,
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_maj", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversations",
                        to="tiers.client",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogue.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation (demande de conseil)",
                "verbose_name_plural": "Conversations (demandes de conseil)",
                "ordering": ["-date_maj"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "auteur_type",
                    models.CharField(
                        choices=[("CLIENT", "Client"), ("EQUIPE", "Équipe")],
                        max_length=6,
                    ),
                ),
                ("texte", models.TextField()),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("lu", models.BooleanField(default=False)),
                (
                    "auteur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="messagerie.conversation",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "id"],
            },
        ),
    ]
