# Generated by Django 5.2.17 on 2026-09-28 01:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0001_initial"),
        ("tiers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name="N° commande",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("RECUE", "Reçue"),
                            ("CONFIRMEE", "Confirmée"),
                            ("PREPARATION", "En préparation"),
                            ("PRETE", "Prête (retrait / expédition)"),
                            ("LIVREE", "Livrée"),
                            ("ANNULEE", "Annulée"),
                        ],
                        default="RECUE",
                        max_length=12,
                    ),
                ),
                (
                    "mode_livraison",
                    models.CharField(
                        choices=[
                            ("RETRAIT", "Retrait en boutique"),
                            ("LIVRAISON", "Livraison à domicile"),
                        ],
                        default="RETRAIT",
                        max_length=10,
                    ),
                ),
                ("adresse_livraison", models.TextField(blank=True)),
                (
                    "message_client",
                    models.TextField(blank=True, verbose_name="Message du client"),
                ),
                ("note_interne", models.TextField(blank=True)),
                (
                    "date_maj",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Dernière mise à jour"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commandes",
                        to="tiers.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commande en ligne",
                "verbose_name_plural": "Commandes en ligne",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_document",
                    models.CharField(
                        choices=[("PRO", "Proforma"), ("FAC", "Facture")],
                        default="FAC",
                        max_length=3,
                        verbose_name="Type",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=30,
                        null=True,
                        unique=True,
                        verbose_name="N°",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "date_echeance",
                    models.DateField(
                        blank=True,
                        help_text="Date limite de paiement (facture) ou de validité (proforma).",
                        null=True,
                        verbose_name="Échéance / validité",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("VALIDE", "Validé"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="BROUILLON",
                        editable=False,
                        max_length=10,
                    ),
                ),
                ("objet", models.CharField(blank=True, max_length=200)),
                (
                    "notes",
                    models.TextField(
                        blank=True, verbose_name="Notes (imprimées sur le document)"
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "date_validation",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="documents",
                        to="tiers.client",
                    ),
                ),
                (
                    "commande_origine",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="factures",
                        to="ventes.commande",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proforma_origine",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="factures_generees",
                        to="ventes.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facture / Proforma",
                "verbose_name_plural": "Factures & Proformas",
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="LigneCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField(default=1)),
                ("prix_unitaire", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="ventes.commande",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogue.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne de commande",
            },
        ),
        migrations.CreateModel(
            name="LigneDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Désignation"
                    ),
                ),
                (
                    "quantite",
                    models.PositiveIntegerField(default=1, verbose_name="Qté"),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="P.U. HT",
                    ),
                ),
                (
                    "remise_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Remise %",
                    ),
                ),
                (
                    "taux_tva",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="TVA %",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="ventes.document",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogue.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ligne",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Reglement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("montant", models.DecimalField(decimal_places=0, max_digits=12)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("ESP", "Espèces"),
                            ("OM", "Orange Money"),
                            ("MOOV", "Moov Money"),
                            ("CB", "Carte bancaire"),
                            ("VIR", "Virement"),
                            ("CHQ", "Chèque"),
                        ],
                        default="ESP",
                        max_length=4,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Réf. transaction"
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reglements",
                        to="ventes.document",
                    ),
                ),
            ],
            options={
                "verbose_name": "Règlement",
            },
        ),
    ]
