# Generated by Django 5.2.17 on 2026-09-28 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                (
                    "ordre",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Ordre d'affichage"
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
                "ordering": ["ordre", "nom"],
            },
        ),
        migrations.CreateModel(
            name="Marque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=80, unique=True)),
            ],
            options={
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Référence"
                    ),
                ),
                ("nom", models.CharField(max_length=200, verbose_name="Désignation")),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "type_produit",
                    models.CharField(
                        choices=[
                            ("TEL", "Téléphone"),
                            ("ACC", "Accessoire"),
                            ("PIE", "Pièce détachée"),
                            ("SER", "Service (main d'œuvre...)"),
                        ],
                        default="TEL",
                        max_length=3,
                        verbose_name="Type",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "caracteristiques",
                    models.TextField(
                        blank=True,
                        help_text="Une caractéristique par ligne, ex : « Écran : 6,5 pouces »",
                        verbose_name="Caractéristiques techniques",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="produits/")),
                (
                    "prix_achat",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="Prix d'achat",
                    ),
                ),
                (
                    "prix_vente",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="Prix de vente"
                    ),
                ),
                (
                    "stock",
                    models.IntegerField(
                        default=0, editable=False, verbose_name="Stock actuel"
                    ),
                ),
                (
                    "stock_alerte",
                    models.PositiveIntegerField(
                        default=2, verbose_name="Seuil d'alerte"
                    ),
                ),
                (
                    "garantie_mois",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Garantie (mois)"
                    ),
                ),
                (
                    "visible_portail",
                    models.BooleanField(
                        default=True, verbose_name="Visible sur le site public"
                    ),
                ),
                ("actif", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produits",
                        to="catalogue.categorie",
                    ),
                ),
                (
                    "marque",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="catalogue.marque",
                    ),
                ),
            ],
            options={
                "ordering": ["nom"],
            },
        ),
    ]
