# Generated by Django 5.2.17 on 2026-09-28 01:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalogue", "0001_initial"),
        ("stock", "0001_initial"),
        ("tiers", "0001_initial"),
        ("ventes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DossierMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=30,
                        unique=True,
                        verbose_name="N° dossier",
                    ),
                ),
                (
                    "code_suivi",
                    models.CharField(
                        blank=True, editable=False, max_length=12, unique=True
                    ),
                ),
                ("marque", models.CharField(max_length=60)),
                ("modele", models.CharField(max_length=100, verbose_name="Modèle")),
                (
                    "imei",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="IMEI / N° de série"
                    ),
                ),
                ("couleur", models.CharField(blank=True, max_length=40)),
                (
                    "code_deverrouillage",
                    models.CharField(
                        blank=True,
                        help_text="Confidentiel : jamais affiché sur le portail public.",
                        max_length=40,
                        verbose_name="Code de déverrouillage",
                    ),
                ),
                (
                    "accessoires_deposes",
                    models.CharField(
                        blank=True,
                        help_text="Ex : chargeur, coque, carte SIM, carte mémoire...",
                        max_length=255,
                        verbose_name="Accessoires déposés",
                    ),
                ),
                (
                    "etat_visuel",
                    models.TextField(
                        blank=True, verbose_name="État visuel à la réception"
                    ),
                ),
                (
                    "panne_declaree",
                    models.TextField(verbose_name="Panne déclarée par le client"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("RECU", "Appareil reçu"),
                            ("DIAGNOSTIC", "Diagnostic en cours"),
                            ("DEVIS", "Devis en attente d'accord"),
                            ("ATTENTE_PIECE", "En attente de pièce"),
                            ("REPARATION", "Réparation en cours"),
                            ("PRET", "Réparé — prêt à être retiré"),
                            ("IRREPARABLE", "Irréparable — à retirer"),
                            ("RESTITUE", "Restitué au client"),
                        ],
                        default="RECU",
                        max_length=15,
                    ),
                ),
                ("diagnostic", models.TextField(blank=True)),
                (
                    "travaux_effectues",
                    models.TextField(blank=True, verbose_name="Travaux effectués"),
                ),
                (
                    "devis_montant",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=12,
                        null=True,
                        verbose_name="Montant du devis",
                    ),
                ),
                (
                    "devis_accepte",
                    models.BooleanField(
                        blank=True,
                        null=True,
                        verbose_name="Devis accepté par le client",
                    ),
                ),
                (
                    "acompte",
                    models.DecimalField(decimal_places=0, default=0, max_digits=12),
                ),
                ("sous_garantie", models.BooleanField(default=False)),
                (
                    "date_depot",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date de dépôt"
                    ),
                ),
                (
                    "date_prevue",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de retrait prévue"
                    ),
                ),
                (
                    "date_restitution",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dossiers_maintenance",
                        to="tiers.client",
                    ),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dossiers_maintenance",
                        to="ventes.document",
                    ),
                ),
                (
                    "technicien",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dossiers_maintenance",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dossier de maintenance",
                "verbose_name_plural": "Dossiers de maintenance",
                "ordering": ["-date_depot"],
            },
        ),
        migrations.CreateModel(
            name="HistoriqueMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("RECU", "Appareil reçu"),
                            ("DIAGNOSTIC", "Diagnostic en cours"),
                            ("DEVIS", "Devis en attente d'accord"),
                            ("ATTENTE_PIECE", "En attente de pièce"),
                            ("REPARATION", "Réparation en cours"),
                            ("PRET", "Réparé — prêt à être retiré"),
                            ("IRREPARABLE", "Irréparable — à retirer"),
                            ("RESTITUE", "Restitué au client"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "commentaire",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Commentaire (visible par le client)",
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique",
                        to="maintenance.dossiermaintenance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Étape de suivi",
                "verbose_name_plural": "Historique de suivi",
                "ordering": ["date", "id"],
            },
        ),
        migrations.CreateModel(
            name="PieceUtilisee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField(default=1)),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces",
                        to="maintenance.dossiermaintenance",
                    ),
                ),
                (
                    "mouvement",
                    models.OneToOneField(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="stock.mouvementstock",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalogue.produit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce utilisée",
                "verbose_name_plural": "Pièces utilisées",
            },
        ),
    ]
