# Generated by Django 5.2.17 on 2026-09-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_client",
                    models.CharField(
                        choices=[("PART", "Particulier"), ("ENTR", "Entreprise")],
                        default="PART",
                        max_length=4,
                        verbose_name="Type",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=150, verbose_name="Nom / Raison sociale"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        db_index=True, max_length=30, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                ("adresse", models.TextField(blank=True)),
                (
                    "ifu",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="N° IFU (entreprise)"
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=150, verbose_name="Raison sociale"),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Personne à contacter"
                    ),
                ),
                (
                    "telephone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Téléphone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                ("adresse", models.TextField(blank=True)),
                ("pays", models.CharField(blank=True, max_length=60)),
                ("notes", models.TextField(blank=True)),
                ("actif", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["nom"],
            },
        ),
    ]
